---
- name: play 1- Configure Apache and Tomcat for webserver
  hosts: xyz-com-node
  become: yes
  roles:
    - tomcat7  

- name: "play 2- Copy the code-war file to tomcat Servers"
  hosts: xyz-com-node
  become: yes
  tasks:
    - name: Download code and pate to tomcat server
      get_url:
        url: https://manoj-1.s3.ap-south-1.amazonaws.com/trainingwale.war
        dest: /usr/share/tomcat/webapps  
